"""Edge case (mrmr_audit_2026-07-20 edge_cases.md): FE family double-counting between
fe_pairwise_modular and fe_conditional_gate.

Both families are reachable when ``fe_discrete_structural_operators_enable=True`` (the default,
grouping four discrete-structural FE families as commonly co-enabled per
``_param_accuracy_warnings.py``'s registry). The task brief's named risk is "two FE families that
could double-count the same signal": if y is generated by a MIX of a modular-arithmetic pattern
(pairwise_modular's own detection target) and a threshold-gated interaction (conditional_gate's own
detection target) over the SAME underlying raw columns, both families' own MI-based detectors can
legitimately fire and propose partially-overlapping engineered candidates. MRMR's global redundancy
gate (not each family's own local accuracy gate) is the mechanism that must then keep only the
stronger of the two rather than selecting both near-redundant engineered duplicates and inflating
apparent ``support_`` size.
"""

from __future__ import annotations

import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

from mlframe.feature_selection.filters.mrmr import MRMR


def _mixed_modular_and_gate_fixture(seed: int = 1, n: int = 6000, m: int = 7):
    """y is the OR of a pure modular-arithmetic event ((a+b) mod m >= m//2, pairwise_modular's own
    detection target) and a threshold-gated interaction (y = a if c>tau else b, conditional_gate's
    own detection target) -- both over the SAME raw columns a/b, so both families' own detectors
    have genuine, partially-overlapping signal to catch."""
    rng = np.random.default_rng(seed)
    a = rng.integers(0, 100, n)
    b = rng.integers(0, 100, n)
    mod_sig = ((a + b) % m >= (m // 2)).astype(int)
    c = rng.uniform(0.0, 1.0, n)
    tau = 0.5
    gate_val = np.where(c > tau, a, b)
    gate_sig = (gate_val > np.median(gate_val)).astype(int)
    y = ((mod_sig + gate_sig) >= 1).astype(int)
    X = pd.DataFrame(
        {
            "a": a.astype(float),
            "b": b.astype(float),
            "c": c,
            "extra": (a % 2).astype(float),
            "n0": rng.integers(0, 50, n).astype(float),
            "n1": rng.integers(0, 50, n).astype(float),
        }
    )
    return X, y


def _kw(**overrides):
    """Fast-fitting default MRMR constructor kwargs, overridable per test."""
    base = dict(
        random_state=42,
        verbose=0,
        n_jobs=1,
        full_npermutations=2,
        baseline_npermutations=2,
        fe_max_steps=1,
        skip_retraining_on_same_content=False,
        fe_discrete_structural_operators_enable=True,
        fe_pairwise_modular_enable=True,
        fe_conditional_gate_enable=True,
    )
    base.update(overrides)
    return base


def test_both_families_propose_candidates_on_the_mixed_fixture():
    """Sanity gate: on this fixture BOTH families' own MI-based detectors must actually fire (else
    the redundancy-gate assertion below would be vacuous -- proving nothing competed)."""
    X, y = _mixed_modular_and_gate_fixture()
    m = MRMR(**_kw())
    m.fit(X, y)

    pairwise_modular = list(getattr(m, "pairwise_modular_features_", []) or [])
    conditional_gate = list(getattr(m, "conditional_gate_features_", []) or [])
    assert pairwise_modular, "pairwise_modular must propose at least one candidate on its own modular-arithmetic signal component"
    assert conditional_gate, "conditional_gate must propose at least one candidate on its own threshold-gated signal component"


def test_redundancy_gate_does_not_select_both_competing_engineered_families():
    """PRIMARY GATE: MRMR's redundancy gate must not select BOTH a pairwise_modular engineered
    column AND a conditional_gate engineered column into final support_ when they are near-redundant
    duplicates of overlapping signal -- it must keep only the stronger one, not double-count."""
    X, y = _mixed_modular_and_gate_fixture()
    m = MRMR(**_kw())
    m.fit(X, y)

    pairwise_modular = set(getattr(m, "pairwise_modular_features_", []) or [])
    conditional_gate = set(getattr(m, "conditional_gate_features_", []) or [])
    final_names = set(str(s) for s in m.get_feature_names_out())

    selected_modular = final_names & pairwise_modular
    selected_gate = final_names & conditional_gate

    assert not (selected_modular and selected_gate), (
        f"MRMR selected engineered columns from BOTH competing families -- possible double-counting: "
        f"modular={selected_modular}, gate={selected_gate}, full support={sorted(final_names)}"
    )
    # the fit must still have selected SOMETHING useful (not an empty/degenerate support as a cheap
    # way to vacuously satisfy the assertion above).
    assert len(final_names) >= 1
